# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Docker.gitlab-ci.yml

# Build a Docker image with CI/CD and push to the GitLab registry.
# Docker-in-Docker documentation: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
#
# This template uses one generic job with conditional builds
# for the default branch and all other (MR) branches.

docker-build-paper:
  # Use the official docker image.
  image: docker:cli
  stage: build
  tags:
    - docker

  variables:
    PAPERMC_PROJECT: "paper"
    DOCKER_HOST: "unix:///var/run/docker.sock"
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE/$PAPERMC_PROJECT:$CI_COMMIT_REF_SLUG
    
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # All branches are tagged with $DOCKER_IMAGE_NAME (defaults to commit ref slug)
  # Default branch is also tagged with `latest`
  script:
    - docker build --build-arg PAPERMC_PROJECT="$PAPERMC_PROJECT" --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE/$PAPERMC_PROJECT:latest"
        docker push "$CI_REGISTRY_IMAGE/$PAPERMC_PROJECT:latest"
      fi
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

docker-build-velocity:
  # Use the official docker image.
  image: docker:cli
  stage: build
  tags:
    - docker

  variables:
    PAPERMC_PROJECT: "velocity"
    DOCKER_HOST: "unix:///var/run/docker.sock"
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE/$PAPERMC_PROJECT:$CI_COMMIT_REF_SLUG
    
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # All branches are tagged with $DOCKER_IMAGE_NAME (defaults to commit ref slug)
  # Default branch is also tagged with `latest`
  script:
    - docker build --build-arg PAPERMC_PROJECT="$PAPERMC_PROJECT" --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE/$PAPERMC_PROJECT:latest"
        docker push "$CI_REGISTRY_IMAGE/$PAPERMC_PROJECT:latest"
      fi
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

docker-build-waterfall:
  # Use the official docker image.
  image: docker:cli
  stage: build
  tags:
    - docker

  variables:
    PAPERMC_PROJECT: "waterfall"
    DOCKER_HOST: "unix:///var/run/docker.sock"
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE/$PAPERMC_PROJECT:$CI_COMMIT_REF_SLUG
    
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # All branches are tagged with $DOCKER_IMAGE_NAME (defaults to commit ref slug)
  # Default branch is also tagged with `latest`
  script:
    - docker build --build-arg PAPERMC_PROJECT="$PAPERMC_PROJECT" --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE/$PAPERMC_PROJECT:latest"
        docker push "$CI_REGISTRY_IMAGE/$PAPERMC_PROJECT:latest"
      fi
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile